openapi: 3.0.0
info:
  description: ''
  version: '1.0'
  title: drt API
paths:
  /api/announcement:
    get:
      tags:
        - announcement
      parameters:
        - in: header
          name: page
          schema:
            type: integer
          required: true
      responses:
        200:
          description: success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/GetAnnouncements'
        400:
          description: error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
    post:
      tags:
        - announcement
      parameters:
        - in: query
          name: name
          schema:
            type: string
        - in: query
          name: role
          schema:
            type: string
        - in: query
          name: hash
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/AddAnnoucement'
      responses:
        200:
          description: success
          content:
            application/json:
              schema:
                type: object
                properties:
                  result:
                    type: boolean
    delete:
      tags:
        - announcement
      parameters:
        - in: query
          name: id
          schema:
            type: string
      responses:
        200:
          description: success
          content:
            application/json:
              schema:
                type: object
                properties:
                  result:
                    type: boolean
  /api/auth:
    post:
      tags:
        - auth
      parameters:
        - in: query
          name: name
          schema:
            type: string
        - in: query
          name: password
          schema:
            type: string
      responses:
        200:
          description: success
          content:
            application/json:
              schema:
                type: object
                properties:
                  is_authorized:
                    type: boolean
                  Name:
                    type: string
                    example: Stephan
                  Role:
                    type: integer
                    example: 1
  /api/check:
    post:
      tags:
        - auth
      parameters:
        - in: query
          name: name
          schema:
            type: string
        - in: query
          name: role
          schema:
            type: string
        - in: query
          name: hash
          schema:
            type: string
      responses:
        200:
          description: success
          content:
            application/json:
              schema:
                type: object
                properties:
                  is_authorized:
                    type: boolean
components:
  schemas:
    ErrorResponse:
      type: object
      properties:
        errors:
          type: array
          items:
            type: object
            properties:
              code:
                type: string
              message:
                type: string
    GetAnnouncements:
      type: object
      properties:
        count:
          type: integer
          example: 15
        announcements:
          type: array
          items:
            properties:
              id:
                type: integer
              username:
                type: string
              title:
                type: string
              text:
                type: string
              date:
                type: string
                example: "2020-20-20"
    AddAnnoucement:
      type: object
      properties:
        title:
          type: string
        username:
          type: string
        text:
          type: string