openapi: 3.0.0
info:
  description: ''
  version: '1.0'
  title: drt API
paths:
  /announcements:
    get:
      tags:
        - announcement
      parameters:
        - in: header
          name: page
          schema:
            type: integer
          required: true
      responses:
        200:
          description: success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/GetAnnouncements'
        400:
          description: error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
    post:
      tags:
        - announcement
      parameters:
        - in: header
          name: page
          schema:
            type: integer
          required: true
      responses:
        200:
          description: success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/InsertAnnouncements'

components:
  schemas:
    ErrorResponse:
      type: object
      properties:
        errors:
          type: array
          items:
            type: object
            properties:
              code:
                type: string
              message:
                type: string
    GetAnnouncements:
      type: object
      properties:
        count:
          type: integer
          example: 15
        announcements:
          type: array
          items:
            properties:
              title:
                type: string
              text:
                type: string
              date:
                type: string
                example: "2020-20-20"
    InsertAnnouncements:
      type: object
      properties:
        correct:
          type: boolean
          example: false
        invalid_fields:
          type: array
          items: 
            type: string
    
