openapi: 3.0.0
info:
  description: ''
  version: '1.0'
  title: drt API
paths:
  /get_count:
    get:
      tags:
        - announcement
      parameters:
        - in: header
          name: page
          schema:
            type: integer
          required: true
      responses:
        200:
          description: success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/GetAnnouncements'
        400:
          description: error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
  /auth:
    post:
      tags:
        - auth
      parameters:
        - in: query
          name: name
          schema:
            type: string
        - in: query
          name: password
          schema:
            type: string
      responses:
        200:
          description: success
          content:
            application/json:
              schema:
                type: object
                properties:
                  is_authorized:
                    type: boolean
                  Name:
                    type: string
                    example: Stephan
                  Role:
                    type: integer
                    example: 1
  /check:
    post:
      tags:
        - auth
      parameters:
        - in: query
          name: name
          schema:
            type: string
        - in: query
          name: role
          schema:
            type: string
        - in: query
          name: hash
          schema:
            type: string
      responses:
        200:
          description: success
          content:
            application/json:
              schema:
                type: object
                properties:
                  is_authorized:
                    type: boolean
components:
  schemas:
    ErrorResponse:
      type: object
      properties:
        errors:
          type: array
          items:
            type: object
            properties:
              code:
                type: string
              message:
                type: string
    GetAnnouncements:
      type: object
      properties:
        count:
          type: integer
          example: 15
        announcements:
          type: array
          items:
            properties:
              title:
                type: string
              text:
                type: string
              date:
                type: string
                example: "2020-20-20"
    
